# Generated by Django 3.1.4 on 2020-12-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel5',
            name='SmallCategory',
        ),
        migrations.AlterField(
            model_name='blogmodel5',
            name='category',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('DataScience', 'DataScience'), ('FIRE', 'FIRE'), ('Education', 'Education'), ('PythonHuck', 'PythonHuck'), ('MathPhys', 'MathPhys'), ('Other', 'Other')], max_length=50),
        ),
    ]
