# Generated by Django 3.1.4 on 2020-12-26 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0003_aboutmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmodel',
            name='category',
        ),
    ]
