# Generated by Django 3.1.4 on 2021-01-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0006_reviewmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel5',
            name='introduction',
            field=models.TextField(default='<div id="toc"></div>'),
        ),
    ]
