# Generated by Django 3.1.4 on 2021-01-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0007_blogmodel5_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel5',
            name='introduction',
            field=models.TextField(),
        ),
    ]
