# Generated by Django 3.1.4 on 2021-01-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0008_auto_20210112_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurpleAdvertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('DataScience', 'DataScience'), ('FIRE', 'FIRE'), ('Education', 'Education'), ('PythonHuck', 'PythonHuck'), ('MathPhys', 'MathPhys'), ('Other', 'Other')], max_length=50)),
                ('advretising', models.TextField()),
            ],
        ),
    ]
