# Generated by Django 3.1.4 on 2021-01-14 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0009_purpleadvertising'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurpleAdvertising',
        ),
    ]
