# Generated by Django 3.1.4 on 2021-01-22 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0012_blogmodel6'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogModel5',
        ),
        migrations.AddField(
            model_name='blogmodel6',
            name='advertising',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Diary.advertising', verbose_name='Advertising'),
        ),
    ]
