# Generated by Django 3.1.4 on 2021-01-23 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Diary', '0013_auto_20210123_0036'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewModel',
        ),
    ]
